### ISSUE TITLE
[Bug] Video Preview Player Does Not Allow Scrubbing

### ISSUE THREAD

**Issue by wuwendell** [rolson24/BWCT-tracker#8]
Can't go back to previously loaded sections of video, despite the backend processor muxing in 10 second increments.

**Comment by rolson24** [comment]
I fixed this by changing the Recording device to use the hardware encoder to encode the videos into h264 and then I went back to the HTML <video> element.

**Comment by wuwendell** [comment]
boo no pull request associated with issue before closing >:[
